# Generated by Django 4.2 on 2023-04-17 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('county_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userContact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
